### ISSUE TITLE
大神,为何不采用前后端分离

### ISSUE THREAD

**Issue by UvDreamed** [deno-china/website#1]
大神为何不采用前后端分离的方式做中文社区,这样可以更多人加入进来

**Comment by manyuanrong** [comment]
考虑到社区网站，SEO非常重要，现在用一些前后端分离的技术栈，要满足SEO必须要SSR，但目前Deno兼容React和Vue还比较麻烦。
后面我会研究一下Node.js库和deno的兼容方法

**Comment by manyuanrong** [comment]
Deno目前的模板引擎不好用。现在前端分离出去了。针对SEO会单独写一个SEO层来做
