### ISSUE TITLE
deno的依赖下载失败有什么解决办法吗

### ISSUE THREAD

**Issue by towelong** [deno-china/website#22]
![Snipaste_2020-05-18_08-21-09](https://user-images.githubusercontent.com/41502558/82163950-a1a0fd00-98e0-11ea-9990-bf7268bc4ade.png)

**Comment by zhmushan** [comment]
走代理吧....

**Comment by towelong** [comment]
> 走代理吧....

行吧 我试试看  我刚才下载oak那个依赖是可以下的，但是基础库的那个http下不了，不知道什么问题

**Comment by zhmushan** [comment]
@ToWeLong 你拼错了
https://deno.land/std/http/server.ts
